repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        exclude: 'node_modules'
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
        exclude: 'node_modules'
      - id: file-contents-sorter
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: forbid-submodules
      - id: mixed-line-ending
        exclude: 'node_modules'
      - id: name-tests-test
      - id: no-commit-to-branch
      - id: sort-simple-yaml
      - id: trailing-whitespace
        exclude: 'node_modules'

  # Local hooks
  - repo: local
    hooks:
      - id: checkov
        name: checkov
        entry: mise
        args:
          - run
          - checkov
        language: system
        always_run: true
        pass_filenames: false
      - id: prettier
        name: prettier
        entry: mise
        args:
          - run
          - prettier-write-all
        language: system
        always_run: true
        pass_filenames: false
      - id: markdownlint
        name: markdownlint
        entry: mise
        args:
          - run
          - markdownlint-fix-all
        language: system
        files: '\.md$'
        pass_filenames: false
      - id: actionlint
        name: actionlint
        entry: mise
        args:
          - run
          - actionlint
        language: system
        pass_filenames: false
        always_run: true
      - id: shellcheck
        name: shellcheck
        entry: mise
        args:
          - run
          - shellcheck
        language: system
        pass_filenames: true
        files: '\.sh$'
      - id: golangci-lint
        name: golangci-lint
        entry: mise
        args:
          - run
          - golangci-lint
        language: system
        pass_filenames: true
        files: '\.go$'
      - id: gci
        name: gci
        entry: mise
        args:
          - run
          - gci
        language: system
        pass_filenames: true
        files: '\.go$'
      - id: test
        name: test
        entry: mise
        args:
          - run
          - test
        language: system
        always_run: true
        pass_filenames: false
